INFO:     Started server process [500383]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
INFO:     167.103.88.96:53496 - "GET /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:53496 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     167.103.88.96:53689 - "GET /students/ HTTP/1.1" 200 OK
INFO:     167.103.88.96:54203 - "GET /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:54203 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     167.103.88.96:11263 - "GET /students/ HTTP/1.1" 200 OK
INFO:     104.47.26.62:49642 - "HEAD /docs HTTP/1.1" 200 OK
INFO:     103.214.61.250:38508 - "GET /docs HTTP/1.1" 200 OK
INFO:     103.214.61.250:34822 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     20.212.201.123:27833 - "GET /docs HTTP/1.1" 200 OK
INFO:     103.214.61.250:34848 - "GET /students/ HTTP/1.1" 200 OK
INFO:     20.212.201.123:27836 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     20.212.201.123:27833 - "GET /docs HTTP/1.1" 200 OK
INFO:     20.212.201.123:27833 - "GET /docs HTTP/1.1" 200 OK
INFO:     20.212.201.123:27833 - "GET /docs HTTP/1.1" 200 OK
INFO:     20.212.201.123:27969 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     20.212.201.123:27969 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     20.212.201.123:27969 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     104.47.26.126:32770 - "HEAD /docs HTTP/1.1" 200 OK
INFO:     17.233.89.188:55780 - "GET /docs HTTP/1.1" 200 OK
INFO:     17.233.89.188:55780 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     17.233.89.188:55783 - "GET /students/ HTTP/1.1" 200 OK
INFO:     17.233.89.188:55785 - "GET /students/search/?name=gan HTTP/1.1" 200 OK
INFO:     17.233.89.188:55786 - "GET /students/search/?name=ee HTTP/1.1" 200 OK
INFO:     17.233.89.188:55787 - "GET /students/search/?name=e HTTP/1.1" 200 OK
INFO:     17.233.89.188:55788 - "GET /students/export/?format=pdf HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/routing.py", line 75, in app
    response = await f(request)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/fastapi/routing.py", line 302, in app
    raw_response = await run_endpoint_function(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/fastapi/routing.py", line 215, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 38, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/home/ec2-user/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/home/ec2-user/New_project_1/student_db_api/main.py", line 72, in export_students
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
INFO:     17.233.89.188:55789 - "GET /students/export/?format=csv HTTP/1.1" 200 OK
INFO:     20.15.163.245:42910 - "GET / HTTP/1.1" 404 Not Found
INFO:     167.103.88.96:22908 - "GET /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:22908 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     167.103.88.96:22908 - "GET /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:22908 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     104.47.110.62:62556 - "HEAD /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:55999 - "GET /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:55999 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     4.193.96.14:19729 - "GET /docs HTTP/1.1" 200 OK
INFO:     4.193.96.14:19729 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     4.193.96.14:19728 - "GET /docs HTTP/1.1" 200 OK
INFO:     4.193.96.14:19729 - "GET /docs HTTP/1.1" 200 OK
INFO:     4.193.96.14:19729 - "GET /docs HTTP/1.1" 200 OK
INFO:     4.193.96.14:19729 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     4.193.96.14:19729 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     4.193.96.14:19729 - "GET /openapi.json HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/main.py", line 413, in main
    run(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/main.py", line 580, in run
    server.run()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/New_project_1/student_db_api/main.py", line 11, in <module>
    class StudentModel(BaseModel):
  File "/home/ec2-user/New_project_1/student_db_api/main.py", line 14, in StudentModel
    marks: Dict[str, float]  # Flexible subject names and scores
NameError: name 'Dict' is not defined
INFO:     104.47.110.62:38776 - "HEAD /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:5813 - "GET /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:5813 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     167.103.88.96:8249 - "GET /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:8249 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     205.169.39.16:24376 - "GET / HTTP/1.1" 404 Not Found
INFO:     167.103.88.96:58998 - "GET /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:58998 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [500383]
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/main.py", line 413, in main
    run(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/main.py", line 580, in run
    server.run()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/New_project_1/student_db_api/main.py", line 11, in <module>
    class StudentModel(BaseModel):
  File "/home/ec2-user/New_project_1/student_db_api/main.py", line 14, in StudentModel
    marks: Dict[str, float]  # Flexible subject names and scores
NameError: name 'Dict' is not defined
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/main.py", line 413, in main
    run(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/main.py", line 580, in run
    server.run()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/New_project_1/student_db_api/main.py", line 11, in <module>
    class StudentModel(BaseModel):
  File "/home/ec2-user/New_project_1/student_db_api/main.py", line 14, in StudentModel
    marks: Dict[str, float]  # Flexible subject names and scores
NameError: name 'Dict' is not defined
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/main.py", line 413, in main
    run(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/main.py", line 580, in run
    server.run()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/New_project_1/student_db_api/main.py", line 53, in <module>
    @app.get("/students/", response_model=List[StudentModel])
NameError: name 'List' is not defined
INFO:     Started server process [502748]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
INFO:     167.103.88.96:61554 - "GET /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:61554 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     167.103.88.96:61759 - "GET /students/ HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [502748]
INFO:     Started server process [503308]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
INFO:     167.103.88.96:49663 - "GET /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:49663 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [503308]
INFO:     Started server process [504333]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
INFO:     167.103.88.96:50045 - "GET /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:50045 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     104.47.110.62:29083 - "HEAD /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:65021 - "GET /docs HTTP/1.1" 200 OK
INFO:     167.103.88.96:65021 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     4.193.96.14:33146 - "GET /docs HTTP/1.1" 200 OK
INFO:     4.193.96.14:33146 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     4.193.96.14:33147 - "GET /docs HTTP/1.1" 200 OK
INFO:     4.193.96.14:33147 - "GET /docs HTTP/1.1" 200 OK
INFO:     4.193.96.14:33147 - "GET /docs HTTP/1.1" 200 OK
